---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - include: build_win10.yaml
      vars:
        vcenter_server: "192.168.1.100"
        vcenter_user: "username"
        vcenter_pass: "sekretpassword"
        datacenter_name: "Datacenter"
        cluster_name: "Cluster"
        server_name: "{{ vm_name }}"
        template: "win10_template"
    - name: Refresh Hosts
      meta: refresh_inventory

- hosts: win[0]
  gather_facts: no
  tasks:
    - name: Change Hostname
      win_hostname:
        name: "{{ vm_name }}"

    - name: Reboot - Change Hostname
      win_reboot:
        reboot_timeout: 600

    - name: Join Domain
      win_domain_membership:
        dns_domain_name: malware.ru
        domain_admin_user: Administrator@malware.ru
        domain_admin_password: abc123!!!
        state: domain

    - name: Reboot - Join Domain
      win_reboot:
        reboot_timeout: 600

    - include: winhost_software.yaml

    - include: install_winlogbeat.yaml

    - include: disable_winfirewall.yaml

    - include: misc/disable_defender.yaml
