---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - include: build_win2k16.yaml
      vars:
        vcenter_server: "192.168.1.100"
        vcenter_user: "administrator@vsphere.local"
        vcenter_pass: "SekretPassw0rd!"
        datacenter_name: "Datacenter"
        cluster_name: "Cluster"
        server_name: "win2k16srv-01"
        template: "winsrv2k16_template"
    - name: Refresh Hosts
      meta: refresh_inventory

- hosts: win
  tasks:
    - include: dc_promo.yaml  
      vars:
        temp_address: '{{ inventory_hostname }}'
        dc_address: 192.168.100.210
        dc_netmask_cidr: 24
        dc_gateway: 192.168.100.1
        dc_hostname: 'dc02'
        domain_name: "demo.lab"
        local_admin: '.\localadmin'
        temp_password: 'abc123!!!'
        dc_password: 'abc123!!!'
        recovery_password: 'abc123!!!'
        upstream_dns_1: 192.168.100.1
        upstream_dns_2: 13.1.1.1
        reverse_dns_zone: "192.168.100.0/24"
        ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org,2.us.pool.ntp.org,3.us.pool.ntp.org"

- hosts: dc
  tasks:
    - include: install_software.yaml

- hosts: dc
  tasks:
    - include: git_badblood.yaml
